-- HD_ORGANIZATION_MASTER: tenant profile (single-tenant for this deployment)
CREATE TABLE IF NOT EXISTS HD_ORGANIZATION_MASTER (
    Organization_Id         TEXT PRIMARY KEY,
    Company_Name            TEXT NOT NULL,
    Description             TEXT,
    Portal_Name             TEXT,
    Portal_Url              TEXT,
    Custom_Domain           TEXT,
    Is_Domain_Mapped        TEXT NOT NULL DEFAULT 'N' CHECK (Is_Domain_Mapped IN ('Y', 'N')),
    Alias                   TEXT,
    Edition                 TEXT CHECK (Edition IN ('Free', 'Standard', 'Professional', 'Enterprise')),
    Support_Org_Type        TEXT,
    Industry                TEXT,
    Employee_Count          INTEGER,
    Employee_Count_Range    TEXT,
    Country                 TEXT,
    State                   TEXT,
    City                    TEXT,
    Street                  TEXT,
    Zip_Code                TEXT,
    Phone_Number            TEXT,
    Mobile                  TEXT,
    Fax                     TEXT,
    Website                 TEXT,
    Primary_Contact_Email   TEXT,
    Currency_Code           TEXT,
    Currency_Symbol         TEXT,
    Currency_Locale         TEXT,
    Time_Zone               TEXT,
    Logo_Url                TEXT,
    Favicon_Url             TEXT,
    Is_Sandbox_Portal       TEXT NOT NULL DEFAULT 'N' CHECK (Is_Sandbox_Portal IN ('Y', 'N')),
    Is_Default_Portal       TEXT NOT NULL DEFAULT 'Y' CHECK (Is_Default_Portal IN ('Y', 'N')),
    Created_By              TEXT,
    Created_Time            TEXT NOT NULL DEFAULT (datetime('now')),
    Modified_By             TEXT,
    Modified_Time           TEXT,
    Is_Deleted              TEXT NOT NULL DEFAULT 'N' CHECK (Is_Deleted IN ('Y', 'N'))
);
