/**
 * HD_* table names, centralized so repositories never hard-code raw strings.
 * Naming/schema source of truth: docs/Zoho_Desk_Table_Config.xlsx
 */
const DB_TABLES = {
    ORGANIZATION: "HD_ORGANIZATION_MASTER",
    DEPARTMENT: "HD_DEPARTMENT_MASTER",
    ROLE: "HD_ROLE_MASTER",
    AGENT: "HD_AGENT_MASTER",
    BANK: "HD_BANK_MASTER",
    BANK_RESOURCE_MAP: "HD_BANK_RESOURCE_MAP",
    MAIL_REPLY_ADDRESS: "HD_MAIL_REPLY_ADDRESS",
    CONTACT: "HD_CONTACT_MASTER",
    TICKET: "HD_TICKET_MASTER",
    TICKET_CONVERSATION: "HD_TICKET_CONVERSATION",
    TICKET_THREAD: "HD_TICKET_THREAD",
    TICKET_COMMENT: "HD_TICKET_COMMENT",
    TICKET_HISTORY: "HD_TICKET_HISTORY",
    TICKET_METRICS: "HD_TICKET_METRICS",
    TICKET_ATTACHMENT: "HD_TICKET_ATTACHMENT",
    TICKET_CLOCK_SEGMENT: "HD_TICKET_CLOCK_SEGMENT",
    TICKET_ASSIGNMENT: "HD_TICKET_ASSIGNMENT",
    ASSIGNMENT_STATE_LOG: "HD_ASSIGNMENT_STATE_LOG",
    ASSIGNMENT_DEPENDENCY: "HD_ASSIGNMENT_DEPENDENCY",
    TICKET_WORKLOG: "HD_TICKET_WORKLOG",
    PICKLIST_VALUE: "HD_PICKLIST_VALUE",
    PRODUCT: "HD_PRODUCT_MASTER",
    PRIORITY_SLA_CONFIG: "HD_PRIORITY_SLA_CONFIG",
    ESCALATION_LEVEL: "HD_ESCALATION_LEVEL",
    TICKET_ESCALATION: "HD_TICKET_ESCALATION",
    AUTH_LOGIN_EVENT: "HD_AUTH_LOGIN_EVENT",
    AGENT_CREDENTIAL: "HD_AGENT_CREDENTIAL"
};

module.exports = DB_TABLES;
