const ERROR_CODES = {
    // Validation / generic
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    DUPLICATE_KEY: "DUPLICATE_KEY",
    FOREIGN_KEY_VIOLATION: "FOREIGN_KEY_VIOLATION",
    FORBIDDEN: "FORBIDDEN",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

    // Tickets
    TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
    ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",

    // Contacts / Accounts
    CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",

    // Agents / Org structure
    AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
    AGENT_DUPLICATE: "AGENT_DUPLICATE",
    DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",
    DEPARTMENT_DUPLICATE: "DEPARTMENT_DUPLICATE",
    TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
    TEAM_DUPLICATE: "TEAM_DUPLICATE",

    // Settings / picklists
    PICKLIST_VALUE_NOT_FOUND: "PICKLIST_VALUE_NOT_FOUND",
    PICKLIST_VALUE_DUPLICATE: "PICKLIST_VALUE_DUPLICATE",
    PICKLIST_PARENT_NOT_FOUND: "PICKLIST_PARENT_NOT_FOUND",

    // Products
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    PRODUCT_DUPLICATE: "PRODUCT_DUPLICATE",

    // Priority SLA config
    PRIORITY_NOT_FOUND: "PRIORITY_NOT_FOUND",
    PRIORITY_DUPLICATE: "PRIORITY_DUPLICATE",

    // Gmail / ingestion
    GMAIL_NOT_CONFIGURED: "GMAIL_NOT_CONFIGURED",
    GMAIL_AUTH_ERROR: "GMAIL_AUTH_ERROR",
    GMAIL_SYNC_ERROR: "GMAIL_SYNC_ERROR",
    MAIL_REPLY_ADDRESS_NOT_FOUND: "MAIL_REPLY_ADDRESS_NOT_FOUND"
};

module.exports = ERROR_CODES;
